NME = Replace

CXX = c++
CXXFLGS = -Wall -Wextra -Werror -std=c++98 -Iincludes

SRCS =	srcs/main.cpp \
				srcs/Replace.cpp

OBJDIR = objs
OBJS = $(patsubst srcs/%.cpp,$(OBJDIR)/%.o,$(SRCS))

all: $(NME)

$(NME): $(OBJS)
	$(CXX) $(CXXFLGS) $(OBJS) -o $(NME)

$(OBJDIR)/%.o: srcs/%.cpp | $(OBJDIR)
	$(CXX) $(CXXFLGS) -c $< -o $@

$(OBJDIR):
	mkdir -p $(OBJDIR)

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NME)

re: fclean all

.PHONY: all clean fclean re